package com.demo.mapper;

import com.demo.entity.Temp;
import com.demo.entity.TempExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TempMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp
     *
     * @mbg.generated Wed Oct 11 13:53:12 CST 2023
     */
    long countByExample(TempExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp
     *
     * @mbg.generated Wed Oct 11 13:53:12 CST 2023
     */
    int deleteByExample(TempExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp
     *
     * @mbg.generated Wed Oct 11 13:53:12 CST 2023
     */
    int insert(Temp row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp
     *
     * @mbg.generated Wed Oct 11 13:53:12 CST 2023
     */
    int insertSelective(Temp row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp
     *
     * @mbg.generated Wed Oct 11 13:53:12 CST 2023
     */
    List<Temp> selectByExample(TempExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp
     *
     * @mbg.generated Wed Oct 11 13:53:12 CST 2023
     */
    int updateByExampleSelective(@Param("row") Temp row, @Param("example") TempExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp
     *
     * @mbg.generated Wed Oct 11 13:53:12 CST 2023
     */
    int updateByExample(@Param("row") Temp row, @Param("example") TempExample example);
}