package com.demo.entity;

public class Temp {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.x
     *
     * @mbg.generated Wed Oct 11 13:53:12 CST 2023
     */
    private String x;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.x
     *
     * @return the value of temp.x
     *
     * @mbg.generated Wed Oct 11 13:53:12 CST 2023
     */
    public String getX() {
        return x;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.x
     *
     * @param x the value for temp.x
     *
     * @mbg.generated Wed Oct 11 13:53:12 CST 2023
     */
    public void setX(String x) {
        this.x = x == null ? null : x.trim();
    }
}